/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as SocialMediaDesignDubaiRouteImport } from './routes/social-media-design-dubai'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MotionGraphicsAbuDhabiRouteImport } from './routes/motion-graphics-abu-dhabi'
import { Route as LogoDesignUaeRouteImport } from './routes/logo-design-uae'
import { Route as DesignRouteImport } from './routes/design'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSocialMediaSharjahRouteImport } from './routes/services.social-media-sharjah'
import { Route as ServicesSocialMediaDubaiRouteImport } from './routes/services.social-media-dubai'
import { Route as ServicesSocialMediaAbudhabiRouteImport } from './routes/services.social-media-abudhabi'
import { Route as ServicesMotionGraphicsRouteImport } from './routes/services.motion-graphics'
import { Route as ServicesLogoDesignRouteImport } from './routes/services.logo-design'
import { Route as ServicesBrandingAgencyUaeRouteImport } from './routes/services.branding-agency-uae'
import { Route as ServicesAdsDesignRouteImport } from './routes/services.ads-design'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialMediaDesignDubaiRoute = SocialMediaDesignDubaiRouteImport.update({
  id: '/social-media-design-dubai',
  path: '/social-media-design-dubai',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MotionGraphicsAbuDhabiRoute = MotionGraphicsAbuDhabiRouteImport.update({
  id: '/motion-graphics-abu-dhabi',
  path: '/motion-graphics-abu-dhabi',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoDesignUaeRoute = LogoDesignUaeRouteImport.update({
  id: '/logo-design-uae',
  path: '/logo-design-uae',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSocialMediaSharjahRoute =
  ServicesSocialMediaSharjahRouteImport.update({
    id: '/services/social-media-sharjah',
    path: '/services/social-media-sharjah',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSocialMediaDubaiRoute =
  ServicesSocialMediaDubaiRouteImport.update({
    id: '/services/social-media-dubai',
    path: '/services/social-media-dubai',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSocialMediaAbudhabiRoute =
  ServicesSocialMediaAbudhabiRouteImport.update({
    id: '/services/social-media-abudhabi',
    path: '/services/social-media-abudhabi',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesMotionGraphicsRoute = ServicesMotionGraphicsRouteImport.update({
  id: '/services/motion-graphics',
  path: '/services/motion-graphics',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLogoDesignRoute = ServicesLogoDesignRouteImport.update({
  id: '/services/logo-design',
  path: '/services/logo-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBrandingAgencyUaeRoute =
  ServicesBrandingAgencyUaeRouteImport.update({
    id: '/services/branding-agency-uae',
    path: '/services/branding-agency-uae',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAdsDesignRoute = ServicesAdsDesignRouteImport.update({
  id: '/services/ads-design',
  path: '/services/ads-design',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/logo-design-uae': typeof LogoDesignUaeRoute
  '/motion-graphics-abu-dhabi': typeof MotionGraphicsAbuDhabiRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social-media-design-dubai': typeof SocialMediaDesignDubaiRoute
  '/video': typeof VideoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/services/ads-design': typeof ServicesAdsDesignRoute
  '/services/branding-agency-uae': typeof ServicesBrandingAgencyUaeRoute
  '/services/logo-design': typeof ServicesLogoDesignRoute
  '/services/motion-graphics': typeof ServicesMotionGraphicsRoute
  '/services/social-media-abudhabi': typeof ServicesSocialMediaAbudhabiRoute
  '/services/social-media-dubai': typeof ServicesSocialMediaDubaiRoute
  '/services/social-media-sharjah': typeof ServicesSocialMediaSharjahRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/logo-design-uae': typeof LogoDesignUaeRoute
  '/motion-graphics-abu-dhabi': typeof MotionGraphicsAbuDhabiRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social-media-design-dubai': typeof SocialMediaDesignDubaiRoute
  '/video': typeof VideoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/services/ads-design': typeof ServicesAdsDesignRoute
  '/services/branding-agency-uae': typeof ServicesBrandingAgencyUaeRoute
  '/services/logo-design': typeof ServicesLogoDesignRoute
  '/services/motion-graphics': typeof ServicesMotionGraphicsRoute
  '/services/social-media-abudhabi': typeof ServicesSocialMediaAbudhabiRoute
  '/services/social-media-dubai': typeof ServicesSocialMediaDubaiRoute
  '/services/social-media-sharjah': typeof ServicesSocialMediaSharjahRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/logo-design-uae': typeof LogoDesignUaeRoute
  '/motion-graphics-abu-dhabi': typeof MotionGraphicsAbuDhabiRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social-media-design-dubai': typeof SocialMediaDesignDubaiRoute
  '/video': typeof VideoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/services/ads-design': typeof ServicesAdsDesignRoute
  '/services/branding-agency-uae': typeof ServicesBrandingAgencyUaeRoute
  '/services/logo-design': typeof ServicesLogoDesignRoute
  '/services/motion-graphics': typeof ServicesMotionGraphicsRoute
  '/services/social-media-abudhabi': typeof ServicesSocialMediaAbudhabiRoute
  '/services/social-media-dubai': typeof ServicesSocialMediaDubaiRoute
  '/services/social-media-sharjah': typeof ServicesSocialMediaSharjahRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/design'
    | '/logo-design-uae'
    | '/motion-graphics-abu-dhabi'
    | '/portfolio'
    | '/sitemap.xml'
    | '/social-media-design-dubai'
    | '/video'
    | '/blog/$slug'
    | '/checkout/return'
    | '/services/ads-design'
    | '/services/branding-agency-uae'
    | '/services/logo-design'
    | '/services/motion-graphics'
    | '/services/social-media-abudhabi'
    | '/services/social-media-dubai'
    | '/services/social-media-sharjah'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/design'
    | '/logo-design-uae'
    | '/motion-graphics-abu-dhabi'
    | '/portfolio'
    | '/sitemap.xml'
    | '/social-media-design-dubai'
    | '/video'
    | '/blog/$slug'
    | '/checkout/return'
    | '/services/ads-design'
    | '/services/branding-agency-uae'
    | '/services/logo-design'
    | '/services/motion-graphics'
    | '/services/social-media-abudhabi'
    | '/services/social-media-dubai'
    | '/services/social-media-sharjah'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/design'
    | '/logo-design-uae'
    | '/motion-graphics-abu-dhabi'
    | '/portfolio'
    | '/sitemap.xml'
    | '/social-media-design-dubai'
    | '/video'
    | '/blog/$slug'
    | '/checkout/return'
    | '/services/ads-design'
    | '/services/branding-agency-uae'
    | '/services/logo-design'
    | '/services/motion-graphics'
    | '/services/social-media-abudhabi'
    | '/services/social-media-dubai'
    | '/services/social-media-sharjah'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DesignRoute: typeof DesignRoute
  LogoDesignUaeRoute: typeof LogoDesignUaeRoute
  MotionGraphicsAbuDhabiRoute: typeof MotionGraphicsAbuDhabiRoute
  PortfolioRoute: typeof PortfolioRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SocialMediaDesignDubaiRoute: typeof SocialMediaDesignDubaiRoute
  VideoRoute: typeof VideoRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ServicesAdsDesignRoute: typeof ServicesAdsDesignRoute
  ServicesBrandingAgencyUaeRoute: typeof ServicesBrandingAgencyUaeRoute
  ServicesLogoDesignRoute: typeof ServicesLogoDesignRoute
  ServicesMotionGraphicsRoute: typeof ServicesMotionGraphicsRoute
  ServicesSocialMediaAbudhabiRoute: typeof ServicesSocialMediaAbudhabiRoute
  ServicesSocialMediaDubaiRoute: typeof ServicesSocialMediaDubaiRoute
  ServicesSocialMediaSharjahRoute: typeof ServicesSocialMediaSharjahRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-media-design-dubai': {
      id: '/social-media-design-dubai'
      path: '/social-media-design-dubai'
      fullPath: '/social-media-design-dubai'
      preLoaderRoute: typeof SocialMediaDesignDubaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motion-graphics-abu-dhabi': {
      id: '/motion-graphics-abu-dhabi'
      path: '/motion-graphics-abu-dhabi'
      fullPath: '/motion-graphics-abu-dhabi'
      preLoaderRoute: typeof MotionGraphicsAbuDhabiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo-design-uae': {
      id: '/logo-design-uae'
      path: '/logo-design-uae'
      fullPath: '/logo-design-uae'
      preLoaderRoute: typeof LogoDesignUaeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/social-media-sharjah': {
      id: '/services/social-media-sharjah'
      path: '/services/social-media-sharjah'
      fullPath: '/services/social-media-sharjah'
      preLoaderRoute: typeof ServicesSocialMediaSharjahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/social-media-dubai': {
      id: '/services/social-media-dubai'
      path: '/services/social-media-dubai'
      fullPath: '/services/social-media-dubai'
      preLoaderRoute: typeof ServicesSocialMediaDubaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/social-media-abudhabi': {
      id: '/services/social-media-abudhabi'
      path: '/services/social-media-abudhabi'
      fullPath: '/services/social-media-abudhabi'
      preLoaderRoute: typeof ServicesSocialMediaAbudhabiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/motion-graphics': {
      id: '/services/motion-graphics'
      path: '/services/motion-graphics'
      fullPath: '/services/motion-graphics'
      preLoaderRoute: typeof ServicesMotionGraphicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/logo-design': {
      id: '/services/logo-design'
      path: '/services/logo-design'
      fullPath: '/services/logo-design'
      preLoaderRoute: typeof ServicesLogoDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/branding-agency-uae': {
      id: '/services/branding-agency-uae'
      path: '/services/branding-agency-uae'
      fullPath: '/services/branding-agency-uae'
      preLoaderRoute: typeof ServicesBrandingAgencyUaeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ads-design': {
      id: '/services/ads-design'
      path: '/services/ads-design'
      fullPath: '/services/ads-design'
      preLoaderRoute: typeof ServicesAdsDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DesignRoute: DesignRoute,
  LogoDesignUaeRoute: LogoDesignUaeRoute,
  MotionGraphicsAbuDhabiRoute: MotionGraphicsAbuDhabiRoute,
  PortfolioRoute: PortfolioRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SocialMediaDesignDubaiRoute: SocialMediaDesignDubaiRoute,
  VideoRoute: VideoRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ServicesAdsDesignRoute: ServicesAdsDesignRoute,
  ServicesBrandingAgencyUaeRoute: ServicesBrandingAgencyUaeRoute,
  ServicesLogoDesignRoute: ServicesLogoDesignRoute,
  ServicesMotionGraphicsRoute: ServicesMotionGraphicsRoute,
  ServicesSocialMediaAbudhabiRoute: ServicesSocialMediaAbudhabiRoute,
  ServicesSocialMediaDubaiRoute: ServicesSocialMediaDubaiRoute,
  ServicesSocialMediaSharjahRoute: ServicesSocialMediaSharjahRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
